const locationData = {
  "Andhra Pradesh": {
    Anantapur: ["Anantapur", "Guntakal", "Hindupur"],
    Chittoor: ["Chittoor", "Tirupati", "Madanapalle"],
    "East Godavari": ["Kakinada", "Rajahmundry", "Amalapuram"],
    Guntur: ["Guntur", "Tenali", "Narasaraopet"],
    Krishna: ["Vijayawada", "Machilipatnam", "Gudivada"],
    Kurnool: ["Kurnool", "Nandyal", "Adoni"],
    Prakasam: ["Ongole", "Markapur"],
    "Sri Potti Sriramulu Nellore": ["Nellore", "Kavali", "Gudur"],
    Srikakulam: ["Srikakulam", "Palasa", "Amadalavalasa"],
    Visakhapatnam: ["Visakhapatnam", "Bheemunipatnam", "Anakapalle"],
    Vizianagaram: ["Vizianagaram", "Parvathipuram", "Bobbili"],
    "West Godavari": ["Eluru", "Tadepalligudem", "Bhimavaram"],
    "YSR Kadapa": ["Kadapa", "Proddatur", "Pulivendula"],
  },
  "Arunachal Pradesh": {
    Tawang: ["Tawang"],
    "West Kameng": ["Bomdila"],
    "East Kameng": ["Seppa"],
    "Papum Pare": ["Itanagar", "Naharlagun"],
    "Kurung Kumey": ["Koloriang"],
    "Kra Daadi": ["Palin"],
    "Lower Subansiri": ["Ziro"],
    "Upper Subansiri": ["Daporijo"],
    "West Siang": ["Aalo"],
    "East Siang": ["Pasighat"],
    Siang: ["Boleng"],
    "Upper Siang": ["Yingkiong"],
    "Lower Siang": ["Likabali"],
    "Lower Dibang Valley": ["Roing"],
    "Dibang Valley": ["Anini"],
    Anjaw: ["Hawai"],
    Changlang: ["Changlang"],
    Tirap: ["Khonsa"],
    Longding: ["Longding"],
  },
  Assam: {
    Baksa: ["Mushalpur"],
    Barpeta: ["Barpeta", "Howly", "Sarthebari"],
    Biswanath: ["Biswanath Chariali"],
    Bongaigaon: ["Bongaigaon", "Abhayapuri"],
    Cachar: ["Silchar", "Lakhipur"],
    Charaideo: ["Sonari"],
    Chirang: ["Kajolgaon"],
    Darrang: ["Mangaldoi"],
    Dhemaji: ["Dhemaji"],
    Dhubri: ["Dhubri", "Gauripur"],
    Dibrugarh: ["Dibrugarh", "Naharkatia"],
    Goalpara: ["Goalpara"],
    Golaghat: ["Golaghat", "Dergaon"],
    Hailakandi: ["Hailakandi"],
    Hojai: ["Hojai"],
    Jorhat: ["Jorhat", "Mariani", "Teok"],
    "Kamrup Metropolitan": ["Guwahati"],
    "Kamrup Rural": ["Amingaon", "Palashbari"],
    "Karbi Anglong": ["Diphu", "Bokajan"],
    Karimganj: ["Karimganj", "Badarpur"],
    Kokrajhar: ["Kokrajhar"],
    Lakhimpur: ["North Lakhimpur"],
    Majuli: ["Garamur"],
    Morigaon: ["Morigaon"],
    Nagaon: ["Nagaon", "Hojai", "Dhing"],
    Nalbari: ["Nalbari"],
    Sivasagar: ["Sivasagar", "Nazira"],
    Sonitpur: ["Tezpur"],
    "South Salmara-Mankachar": ["Hatsingimari"],
    Tinsukia: ["Tinsukia", "Makum", "Digboi"],
    Udalguri: ["Udalguri"],
    "West Karbi Anglong": ["Hamren"],
  },
  Bihar: {
    Araria: ["Araria", "Forbesganj"],
    Arwal: ["Arwal"],
    Aurangabad: ["Aurangabad"],
    Banka: ["Banka"],
    Begusarai: ["Begusarai"],
    Bhagalpur: ["Bhagalpur", "Naugachhia"],
    Bhojpur: ["Ara"],
    Buxar: ["Buxar"],
    Darbhanga: ["Darbhanga"],
    "East Champaran": ["Motihari", "Raxaul"],
    Gaya: ["Gaya", "Bodh Gaya"],
    Gopalganj: ["Gopalganj"],
    Jamui: ["Jamui"],
    Jehanabad: ["Jehanabad"],
    Kaimur: ["Bhabua"],
    Katihar: ["Katihar", "Manihari"],
    Khagaria: ["Khagaria"],
    Kishanganj: ["Kishanganj"],
    Lakhisarai: ["Lakhisarai"],
    Madhepura: ["Madhepura"],
    Madhubani: ["Madhubani"],
    Munger: ["Munger", "Jamalpur"],
    Muzaffarpur: ["Muzaffarpur"],
    Nalanda: ["Bihar Sharif", "Rajgir"],
    Nawada: ["Nawada"],
    Patna: ["Patna", "Barh"],
    Purnia: ["Purnia"],
    Rohtas: ["Sasaram", "Dehri-on-Sone"],
    Saharsa: ["Saharsa"],
    Samastipur: ["Samastipur"],
    Saran: ["Chhapra", "Revelganj"],
    Sheikhpura: ["Sheikhpura"],
    Sheohar: ["Sheohar"],
    Sitamarhi: ["Sitamarhi"],
    Siwan: ["Siwan"],
    Supaul: ["Supaul"],
    Vaishali: ["Hajipur"],
    "West Champaran": ["Bettiah", "Narkatiaganj"],
  },
  Chhattisgarh: {
    Balod: ["Balod"],
    "Baloda Bazar": ["Baloda Bazar"],
    Balrampur: ["Balrampur"],
    Bastar: ["Jagdalpur"],
    Bemetara: ["Bemetara"],
    Bijapur: ["Bijapur"],
    Bilaspur: ["Bilaspur"],
    Dantewada: ["Dantewada"],
    Dhamtari: ["Dhamtari"],
    Durg: ["Durg", "Bhilai"],
    Gariaband: ["Gariaband"],
    "Gaurela-Pendra-Marwahi": ["Gaurela"],
    "Janjgir-Champa": ["Janjgir"],
    Jashpur: ["Jashpur"],
    Kabirdham: ["Kawardha"],
    Kanker: ["Kanker"],
    Kondagaon: ["Kondagaon"],
    Korba: ["Korba"],
    Koriya: ["Baikunthpur"],
    Mahasamund: ["Mahasamund"],
    Mungeli: ["Mungeli"],
    Narayanpur: ["Narayanpur"],
    Raigarh: ["Raigarh"],
    Raipur: ["Raipur"],
    Rajnandgaon: ["Rajnandgaon"],
    Sukma: ["Sukma"],
    Surajpur: ["Surajpur"],
    Surguja: ["Ambikapur"],
  },
  Goa: {
    "North Goa": ["Panaji", "Mapusa", "Bicholim", "Valpoi"],
    "South Goa": ["Margao", "Vasco da Gama", "Ponda", "Curchorem"],
  },
  Gujarat: {
    Ahmedabad: ["Ahmedabad", "Dholka", "Sanand"],
    Amreli: ["Amreli", "Bagasara"],
    Anand: ["Anand", "Khambhat", "Borsad"],
    Aravalli: ["Modasa"],
    Banaskantha: ["Palanpur", "Deesa"],
    Bharuch: ["Bharuch", "Ankleshwar"],
    Bhavnagar: ["Bhavnagar", "Mahuva"],
    Botad: ["Botad"],
    "Chhota Udaipur": ["Chhota Udaipur"],
    Dahod: ["Dahod"],
    Dang: ["Ahwa"],
    "Devbhoomi Dwarka": ["Dwarka"],
    Gandhinagar: ["Gandhinagar", "Kalol"],
    "Gir Somnath": ["Veraval"],
    Jamnagar: ["Jamnagar", "Dhrol"],
    Junagadh: ["Junagadh", "Keshod"],
    Kheda: ["Nadiad"],
    Kutch: ["Bhuj", "Mandvi"],
    Mahisagar: ["Lunawada"],
    Mehsana: ["Mehsana", "Vijapur"],
    Morbi: ["Morbi"],
    Narmada: ["Rajpipla"],
    Navsari: ["Navsari"],
    Panchmahal: ["Godhra"],
    Patan: ["Patan"],
    Porbandar: ["Porbandar"],
    Rajkot: ["Rajkot", "Gondal"],
    Sabarkantha: ["Himmatnagar"],
    Surat: ["Surat", "Bardoli"],
    Surendranagar: ["Surendranagar"],
    Tapi: ["Vyara"],
    Vadodara: ["Vadodara", "Padra"],
    Valsad: ["Valsad", "Vapi"],
  },
  Haryana: {
    Ambala: ["Ambala", "Naraingarh"],
    Bhiwani: ["Bhiwani", "Loharu"],
    "Charkhi Dadri": ["Charkhi Dadri"],
    Faridabad: ["Faridabad", "Ballabgarh"],
    Fatehabad: ["Fatehabad", "Tohana"],
    Gurugram: ["Gurugram", "Sohna"],
    Hisar: ["Hisar", "Hansi"],
    Jhajjar: ["Jhajjar", "Bahadurgarh"],
    Jind: ["Jind", "Narwana"],
    Kaithal: ["Kaithal", "Pundri"],
    Karnal: ["Karnal", "Taraori"],
    Kurukshetra: ["Kurukshetra", "Thanesar"],
    Mahendragarh: ["Mahendragarh", "Narnaul"],
    Nuh: ["Nuh"],
    Palwal: ["Palwal"],
    Panchkula: ["Panchkula"],
    Panipat: ["Panipat"],
    Rewari: ["Rewari"],
    Rohtak: ["Rohtak"],
    Sirsa: ["Sirsa", "Ellenabad"],
    Sonipat: ["Sonipat", "Gohana"],
    Yamunanagar: ["Yamunanagar", "Jagadhri"],
  },
  "Himachal Pradesh": {
    Bilaspur: ["Bilaspur"],
    Chamba: ["Chamba"],
    Hamirpur: ["Hamirpur"],
    Kangra: ["Dharamshala", "Palampur"],
    Kinnaur: ["Reckong Peo"],
    Kullu: ["Kullu", "Manali"],
    "Lahaul and Spiti": ["Keylong"],
    Mandi: ["Mandi"],
    Shimla: ["Shimla", "Rampur"],
    Sirmaur: ["Nahan", "Paonta Sahib"],
    Solan: ["Solan"],
    Una: ["Una"],
  },
  Jharkhand: {
    Bokaro: ["Bokaro Steel City"],
    Chatra: ["Chatra"],
    Deoghar: ["Deoghar"],
    Dhanbad: ["Dhanbad"],
    Dumka: ["Dumka"],
    "East Singhbhum": ["Jamshedpur"],
    Garhwa: ["Garhwa"],
    Giridih: ["Giridih"],
    Godda: ["Godda"],
    Gumla: ["Gumla"],
    Hazaribagh: ["Hazaribagh"],
    Jamtara: ["Jamtara"],
    Khunti: ["Khunti"],
    Koderma: ["Koderma"],
    Latehar: ["Latehar"],
    Lohardaga: ["Lohardaga"],
    Pakur: ["Pakur"],
    Palamu: ["Daltonganj"],
    Ramgarh: ["Ramgarh"],
    Ranchi: ["Ranchi"],
    Sahebganj: ["Sahebganj"],
    "Seraikela Kharsawan": ["Seraikela"],
    Simdega: ["Simdega"],
    "West Singhbhum": ["Chaibasa"],
  },
  Karnataka: {
    Bagalkot: ["Bagalkot", "Mudhol"],
    Ballari: ["Ballari", "Hospet"],
    Belagavi: ["Belagavi", "Gokak"],
    "Bengaluru Urban": ["Bengaluru"],
    "Bengaluru Rural": ["Dod Ballapur"],
    Bidar: ["Bidar"],
    Chamarajanagar: ["Chamarajanagar"],
    Chikballapur: ["Chikballapur"],
    Chikkamagaluru: ["Chikkamagaluru"],
    Chitradurga: ["Chitradurga"],
    "Dakshina Kannada": ["Mangaluru"],
    Davanagere: ["Davanagere"],
    Dharwad: ["Hubballi", "Dharwad"],
    Gadag: ["Gadag"],
    Hassan: ["Hassan"],
    Haveri: ["Haveri"],
    Kalaburagi: ["Kalaburagi"],
    Kodagu: ["Madikeri"],
    Kolar: ["Kolar"],
    Koppal: ["Koppal"],
    Mandya: ["Mandya"],
    Mysuru: ["Mysuru"],
    Raichur: ["Raichur"],
    Ramanagara: ["Ramanagara"],
    Shivamogga: ["Shivamogga"],
    Tumakuru: ["Tumakuru"],
    Udupi: ["Udupi"],
    "Uttara Kannada": ["Karwar"],
    Vijayapura: ["Vijayapura"],
    Yadgir: ["Yadgir"],
  },
  Kerala: {
    Alappuzha: ["Alappuzha", "Kayamkulam"],
    Ernakulam: ["Kochi", "Muvattupuzha"],
    Idukki: ["Thodupuzha", "Munnar"],
    Kannur: ["Kannur", "Taliparamba"],
    Kasaragod: ["Kasaragod"],
    Kollam: ["Kollam", "Paravur"],
    Kottayam: ["Kottayam", "Pala"],
    Kozhikode: ["Kozhikode"],
    Malappuram: ["Malappuram"],
    Palakkad: ["Palakkad"],
    Pathanamthitta: ["Pathanamthitta"],
    Thiruvananthapuram: ["Thiruvananthapuram"],
    Thrissur: ["Thrissur"],
    Wayanad: ["Kalpetta"],
  },
  "Madhya Pradesh": {
    "Agar Malwa": ["Agar"],
    Alirajpur: ["Alirajpur"],
    Anuppur: ["Anuppur"],
    Ashoknagar: ["Ashoknagar"],
    Balaghat: ["Balaghat"],
    Barwani: ["Barwani"],
    Betul: ["Betul"],
    Bhind: ["Bhind"],
    Bhopal: ["Bhopal"],
    Burhanpur: ["Burhanpur"],
    Chhatarpur: ["Chhatarpur"],
    Chhindwara: ["Chhindwara"],
    Damoh: ["Damoh"],
    Datia: ["Datia"],
    Dewas: ["Dewas"],
    Dhar: ["Dhar"],
    Dindori: ["Dindori"],
    Guna: ["Guna"],
    Gwalior: ["Gwalior"],
    Harda: ["Harda"],
    Hoshangabad: ["Hoshangabad"],
    Indore: ["Indore"],
    Jabalpur: ["Jabalpur"],
    Jhabua: ["Jhabua"],
    Katni: ["Katni"],
    Khandwa: ["Khandwa"],
    Khargone: ["Khargone"],
    Mandla: ["Mandla"],
    Mandsaur: ["Mandsaur"],
    Morena: ["Morena"],
    Narsinghpur: ["Narsinghpur"],
    Neemuch: ["Neemuch"],
    Panna: ["Panna"],
    Raisen: ["Raisen"],
    Rajgarh: ["Rajgarh"],
    Ratlam: ["Ratlam"],
    Rewa: ["Rewa"],
    Sagar: ["Sagar"],
    Satna: ["Satna"],
    Sehore: ["Sehore"],
    Seoni: ["Seoni"],
    Shahdol: ["Shahdol"],
    Shajapur: ["Shajapur"],
    Sheopur: ["Sheopur"],
    Shivpuri: ["Shivpuri"],
    Sidhi: ["Sidhi"],
    Singrauli: ["Singrauli"],
    Tikamgarh: ["Tikamgarh"],
    Ujjain: ["Ujjain"],
    Umaria: ["Umaria"],
    Vidisha: ["Vidisha"],
  },
  Maharashtra: {
    Ahmednagar: ["Ahmednagar", "Shirdi"],
    Akola: ["Akola"],
    Amravati: ["Amravati"],
    Aurangabad: ["Aurangabad"],
    Beed: ["Beed"],
    Bhandara: ["Bhandara"],
    Buldhana: ["Buldhana"],
    Chandrapur: ["Chandrapur"],
    Dhule: ["Dhule"],
    Gadchiroli: ["Gadchiroli"],
    Gondia: ["Gondia"],
    Hingoli: ["Hingoli"],
    Jalgaon: ["Jalgaon"],
    Jalna: ["Jalna"],
    Kolhapur: ["Kolhapur"],
    Latur: ["Latur"],
    Mumbai: ["Mumbai"],
    Nagpur: ["Nagpur"],
    Nanded: ["Nanded"],
    Nandurbar: ["Nandurbar"],
    Nashik: ["Nashik"],
    Osmanabad: ["Osmanabad"],
    Palghar: ["Palghar"],
    Parbhani: ["Parbhani"],
    Pune: ["Pune"],
    Raigad: ["Alibag"],
    Ratnagiri: ["Ratnagiri"],
    Sangli: ["Sangli"],
    Satara: ["Satara"],
    Sindhudurg: ["Sawantwadi"],
    Solapur: ["Solapur"],
    Thane: ["Thane"],
    Wardha: ["Wardha"],
    Washim: ["Washim"],
    Yavatmal: ["Yavatmal"],
  },
  Manipur: {
    Bishnupur: ["Bishnupur"],
    Chandel: ["Chandel"],
    Churachandpur: ["Churachandpur"],
    "Imphal East": ["Porompat"],
    "Imphal West": ["Imphal"],
    Jiribam: ["Jiribam"],
    Kakching: ["Kakching"],
    Kamjong: ["Kamjong"],
    Kangpokpi: ["Kangpokpi"],
    Noney: ["Noney"],
    Pherzawl: ["Pherzawl"],
    Senapati: ["Senapati"],
    Tamenglong: ["Tamenglong"],
    Tengnoupal: ["Tengnoupal"],
    Thoubal: ["Thoubal"],
    Ukhrul: ["Ukhrul"],
  },
  Meghalaya: {
    "East Garo Hills": ["Williamnagar"],
    "East Jaintia Hills": ["Khliehriat"],
    "East Khasi Hills": ["Shillong"],
    "North Garo Hills": ["Resubelpara"],
    "Ri Bhoi": ["Nongpoh"],
    "South Garo Hills": ["Baghmara"],
    "South West Garo Hills": ["Ampati"],
    "South West Khasi Hills": ["Mawkyrwat"],
    "West Garo Hills": ["Tura"],
    "West Jaintia Hills": ["Jowai"],
    "West Khasi Hills": ["Nongstoin"],
  },
  Mizoram: {
    Aizawl: ["Aizawl"],
    Champhai: ["Champhai"],
    Kolasib: ["Kolasib"],
    Lawngtlai: ["Lawngtlai"],
    Lunglei: ["Lunglei"],
    Mamit: ["Mamit"],
    Saiha: ["Saiha"],
    Serchhip: ["Serchhip"],
  },
  Nagaland: {
    Dimapur: ["Dimapur"],
    Kiphire: ["Kiphire"],
    Kohima: ["Kohima"],
    Longleng: ["Longleng"],
    Mokokchung: ["Mokokchung"],
    Mon: ["Mon"],
    Peren: ["Peren"],
    Phek: ["Phek"],
    Tuensang: ["Tuensang"],
    Wokha: ["Wokha"],
    Zunheboto: ["Zunheboto"],
  },
  Odisha: {
    Angul: ["Angul"],
    Balangir: ["Balangir"],
    Balasore: ["Balasore"],
    Bargarh: ["Bargarh"],
    Bhadrak: ["Bhadrak"],
    Boudh: ["Boudh"],
    Cuttack: ["Cuttack"],
    Deogarh: ["Deogarh"],
    Dhenkanal: ["Dhenkanal"],
    Gajapati: ["Paralakhemundi"],
    Ganjam: ["Berhampur"],
    Jagatsinghpur: ["Jagatsinghpur"],
    Jajpur: ["Jajpur"],
    Jharsuguda: ["Jharsuguda"],
    Kalahandi: ["Bhawanipatna"],
    Kandhamal: ["Phulbani"],
    Kendrapara: ["Kendrapara"],
    Kendujhar: ["Kendujhar"],
    Khordha: ["Bhubaneswar"],
    Koraput: ["Koraput"],
    Malkangiri: ["Malkangiri"],
    Mayurbhanj: ["Baripada"],
    Nabarangpur: ["Nabarangpur"],
    Nayagarh: ["Nayagarh"],
    Nuapada: ["Nuapada"],
    Puri: ["Puri"],
    Rayagada: ["Rayagada"],
    Sambalpur: ["Sambalpur"],
    Sonepur: ["Sonepur"],
    Sundargarh: ["Rourkela"],
  },
  Punjab: {
    Amritsar: ["Amritsar"],
    Barnala: ["Barnala"],
    Bathinda: ["Bathinda"],
    Faridkot: ["Faridkot"],
    "Fatehgarh Sahib": ["Fatehgarh Sahib"],
    Fazilka: ["Fazilka"],
    Ferozepur: ["Ferozepur"],
    Gurdaspur: ["Gurdaspur"],
    Hoshiarpur: ["Hoshiarpur"],
    Jalandhar: ["Jalandhar"],
    Kapurthala: ["Kapurthala"],
    Ludhiana: ["Ludhiana"],
    Mansa: ["Mansa"],
    Moga: ["Moga"],
    Muktsar: ["Muktsar"],
    Pathankot: ["Pathankot"],
    Patiala: ["Patiala"],
    Rupnagar: ["Rupnagar"],
    Sangrur: ["Sangrur"],
    "SAS Nagar": ["Mohali"],
    "Shaheed Bhagat Singh Nagar": ["Nawanshahr"],
    "Tarn Taran": ["Tarn Taran"],
  },
  Rajasthan: {
    Ajmer: ["Ajmer"],
    Alwar: ["Alwar"],
    Banswara: ["Banswara"],
    Baran: ["Baran"],
    Barmer: ["Barmer"],
    Bharatpur: ["Bharatpur"],
    Bhilwara: ["Bhilwara"],
    Bikaner: ["Bikaner"],
    Bundi: ["Bundi"],
    Chittorgarh: ["Chittorgarh"],
    Churu: ["Churu"],
    Dausa: ["Dausa"],
    Dholpur: ["Dholpur"],
    Dungarpur: ["Dungarpur"],
    Hanumangarh: ["Hanumangarh"],
    Jaipur: ["Jaipur"],
    Jaisalmer: ["Jaisalmer"],
    Jalore: ["Jalore"],
    Jhalawar: ["Jhalawar"],
    Jhunjhunu: ["Jhunjhunu"],
    Jodhpur: ["Jodhpur"],
    Karauli: ["Karauli"],
    Kota: ["Kota"],
    Nagaur: ["Nagaur"],
    Pali: ["Pali"],
    Pratapgarh: ["Pratapgarh"],
    Rajsamand: ["Rajsamand"],
    "Sawai Madhopur": ["Sawai Madhopur"],
    Sikar: ["Sikar"],
    Sirohi: ["Sirohi"],
    "Sri Ganganagar": ["Sri Ganganagar"],
    Tonk: ["Tonk"],
    Udaipur: ["Udaipur"],
  },
  Sikkim: {
    "East Sikkim": ["Gangtok"],
    "North Sikkim": ["Mangan"],
    "South Sikkim": ["Namchi"],
    "West Sikkim": ["Gyalshing"],
  },
  "Tamil Nadu": {
    Ariyalur: ["Ariyalur"],
    Chengalpattu: ["Chengalpattu"],
    Chennai: ["Chennai"],
    Coimbatore: ["Coimbatore"],
    Cuddalore: ["Cuddalore"],
    Dharmapuri: ["Dharmapuri"],
    Dindigul: ["Dindigul"],
    Erode: ["Erode"],
    Kallakurichi: ["Kallakurichi"],
    Kanchipuram: ["Kanchipuram"],
    Kanyakumari: ["Nagercoil"],
    Karur: ["Karur"],
    Krishnagiri: ["Krishnagiri"],
    Madurai: ["Madurai"],
    Mayiladuthurai: ["Mayiladuthurai"],
    Nagapattinam: ["Nagapattinam"],
    Namakkal: ["Namakkal"],
    Nilgiris: ["Udagamandalam"],
    Perambalur: ["Perambalur"],
    Pudukkottai: ["Pudukkottai"],
    Ramanathapuram: ["Ramanathapuram"],
    Ranipet: ["Ranipet"],
    Salem: ["Salem"],
    Sivaganga: ["Sivaganga"],
    Tenkasi: ["Tenkasi"],
    Thanjavur: ["Thanjavur"],
    Theni: ["Theni"],
    Thoothukudi: ["Thoothukudi"],
    Tiruchirappalli: ["Tiruchirappalli"],
    Tirunelveli: ["Tirunelveli"],
    Tirupathur: ["Tirupathur"],
    Tiruppur: ["Tiruppur"],
    Tiruvallur: ["Tiruvallur"],
    Tiruvannamalai: ["Tiruvannamalai"],
    Tiruvarur: ["Tiruvarur"],
    Vellore: ["Vellore"],
    Viluppuram: ["Viluppuram"],
    Virudhunagar: ["Virudhunagar"],
  },
  Telangana: {
    Adilabad: ["Adilabad"],
    "Bhadradri Kothagudem": ["Kothagudem"],
    Hyderabad: ["Hyderabad"],
    Jagtial: ["Jagtial"],
    Jangaon: ["Jangaon"],
    "Jayashankar Bhupalpally": ["Bhupalpally"],
    "Jogulamba Gadwal": ["Gadwal"],
    Kamareddy: ["Kamareddy"],
    Karimnagar: ["Karimnagar"],
    Khammam: ["Khammam"],
    "Kumuram Bheem": ["Asifabad"],
    Mahabubabad: ["Mahabubabad"],
    Mahbubnagar: ["Mahbubnagar"],
    Mancherial: ["Mancherial"],
    Medak: ["Medak"],
    "Medchal Malkajgiri": ["Medchal"],
    Mulugu: ["Mulugu"],
    Nagarkurnool: ["Nagarkurnool"],
    Nalgonda: ["Nalgonda"],
    Narayanpet: ["Narayanpet"],
    Nirmal: ["Nirmal"],
    Nizamabad: ["Nizamabad"],
    Peddapalli: ["Peddapalli"],
    "Rajanna Sircilla": ["Sircilla"],
    "Ranga Reddy": ["Shamshabad"],
    Sangareddy: ["Sangareddy"],
    Siddipet: ["Siddipet"],
    Suryapet: ["Suryapet"],
    Vikarabad: ["Vikarabad"],
    Wanaparthy: ["Wanaparthy"],
    "Warangal Rural": ["Warangal"],
    "Warangal Urban": ["Warangal"],
    "Yadadri Bhuvanagiri": ["Bhuvanagiri"],
  },
  Tripura: {
    Dhalai: ["Ambassa"],
    Gomati: ["Udaipur"],
    Khowai: ["Khowai"],
    "North Tripura": ["Dharmanagar"],
    Sepahijala: ["Bishalgarh"],
    "South Tripura": ["Belonia"],
    Unakoti: ["Kailasahar"],
    "West Tripura": ["Agartala"],
  },
  "Uttar Pradesh": {
    Agra: ["Agra"],
    Aligarh: ["Aligarh"],
    "Ambedkar Nagar": ["Akbarpur"],
    Amethi: ["Amethi"],
    Amroha: ["Amroha"],
    Auraiya: ["Auraiya"],
    Ayodhya: ["Ayodhya"],
    Azamgarh: ["Azamgarh"],
    Badaun: ["Badaun"],
    Bagpat: ["Bagpat"],
    Bahraich: ["Bahraich"],
    Ballia: ["Ballia"],
    Balrampur: ["Balrampur"],
    Banda: ["Banda"],
    Barabanki: ["Barabanki"],
    Bareilly: ["Bareilly"],
    Basti: ["Basti"],
    Bhadohi: ["Gyanpur"],
    Bijnor: ["Bijnor"],
    Bulandshahr: ["Bulandshahr"],
    Chandauli: ["Chandauli"],
    Chitrakoot: ["Chitrakoot"],
    Deoria: ["Deoria"],
    Etah: ["Etah"],
    Etawah: ["Etawah"],
    Farrukhabad: ["Farrukhabad"],
    Fatehpur: ["Fatehpur"],
    Firozabad: ["Firozabad"],
    "Gautam Buddh Nagar": ["Noida"],
    Ghaziabad: ["Ghaziabad"],
    Ghazipur: ["Ghazipur"],
    Gonda: ["Gonda"],
    Gorakhpur: ["Gorakhpur"],
    Hamirpur: ["Hamirpur"],
    Hapur: ["Hapur"],
    Hardoi: ["Hardoi"],
    Hathras: ["Hathras"],
    Jalaun: ["Orai"],
    Jaunpur: ["Jaunpur"],
    Jhansi: ["Jhansi"],
    Kannauj: ["Kannauj"],
    "Kanpur Dehat": ["Kanpur Dehat"],
    "Kanpur Nagar": ["Kanpur"],
    Kasganj: ["Kasganj"],
    Kaushambi: ["Manjhanpur"],
    Kushinagar: ["Padrauna"],
    "Lakhimpur Kheri": ["Lakhimpur"],
    Lalitpur: ["Lalitpur"],
    Lucknow: ["Lucknow"],
    Maharajganj: ["Maharajganj"],
    Mahoba: ["Mahoba"],
    Mainpuri: ["Mainpuri"],
    Mathura: ["Mathura"],
    Mau: ["Mau"],
    Meerut: ["Meerut"],
    Mirzapur: ["Mirzapur"],
    Moradabad: ["Moradabad"],
    Muzaffarnagar: ["Muzaffarnagar"],
    Pilibhit: ["Pilibhit"],
    Pratapgarh: ["Pratapgarh"],
    Prayagraj: ["Prayagraj"],
    Raebareli: ["Raebareli"],
    Rampur: ["Rampur"],
    Saharanpur: ["Saharanpur"],
    Sambhal: ["Sambhal"],
    "Sant Kabir Nagar": ["Khalilabad"],
    Shahjahanpur: ["Shahjahanpur"],
    Shamli: ["Shamli"],
    Shravasti: ["Bhinga"],
    Siddharthnagar: ["Naugarh"],
    Sitapur: ["Sitapur"],
    Sonbhadra: ["Robertsganj"],
    Sultanpur: ["Sultanpur"],
    Unnao: ["Unnao"],
    Varanasi: ["Varanasi"],
  },
  Uttarakhand: {
    Almora: ["Almora"],
    Bageshwar: ["Bageshwar"],
    Chamoli: ["Gopeshwar"],
    Champawat: ["Champawat"],
    Dehradun: ["Dehradun"],
    Haridwar: ["Haridwar"],
    Nainital: ["Nainital"],
    "Pauri Garhwal": ["Pauri"],
    Pithoragarh: ["Pithoragarh"],
    Rudraprayag: ["Rudraprayag"],
    "Tehri Garhwal": ["Tehri"],
    "Udham Singh Nagar": ["Rudrapur"],
    Uttarkashi: ["Uttarkashi"],
  },
  "West Bengal": {
    Alipurduar: ["Alipurduar"],
    Bankura: ["Bankura"],
    Birbhum: ["Suri"],
    "Cooch Behar": ["Cooch Behar"],
    "Dakshin Dinajpur": ["Balurghat"],
    Darjeeling: ["Darjeeling"],
    Hooghly: ["Chinsurah"],
    Howrah: ["Howrah"],
    Jalpaiguri: ["Jalpaiguri"],
    Jhargram: ["Jhargram"],
    Kalimpong: ["Kalimpong"],
    Kolkata: ["Kolkata"],
    Malda: ["Malda"],
    Murshidabad: ["Berhampore"],
    Nadia: ["Krishnanagar"],
    "North 24 Parganas": ["Barasat"],
    "Paschim Bardhaman": ["Asansol"],
    "Paschim Medinipur": ["Midnapore"],
    "Purba Bardhaman": ["Bardhaman"],
    "Purba Medinipur": ["Tamluk"],
    Purulia: ["Purulia"],
    "South 24 Parganas": ["Alipore"],
    "Uttar Dinajpur": ["Raiganj"],
  },
  "Andaman and Nicobar Islands": {
    Nicobar: ["Car Nicobar"],
    "North and Middle Andaman": ["Mayabunder"],
    "South Andaman": ["Port Blair"],
  },
  Chandigarh: {
    Chandigarh: ["Chandigarh"],
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": ["Silvassa"],
    Daman: ["Daman"],
    Diu: ["Diu"],
  },
  Lakshadweep: {
    Lakshadweep: ["Kavaratti"],
  },
  Delhi: {
    "Central Delhi": ["Daryaganj"],
    "East Delhi": ["Preet Vihar"],
    "New Delhi": ["Connaught Place"],
    "North Delhi": ["Sadar Bazar"],
    "North East Delhi": ["Shahdara"],
    "North West Delhi": ["Kanjhawala"],
    Shahdara: ["Shahdara"],
    "South Delhi": ["Saket"],
    "South East Delhi": ["Sarai Kale Khan"],
    "South West Delhi": ["Dwarka"],
    "West Delhi": ["Rajouri Garden"],
  },
  "Jammu and Kashmir": {
    Anantnag: ["Anantnag"],
    Bandipora: ["Bandipora"],
    Baramulla: ["Baramulla"],
    Budgam: ["Budgam"],
    Doda: ["Doda"],
    Ganderbal: ["Ganderbal"],
    Jammu: ["Jammu"],
    Kathua: ["Kathua"],
    Kishtwar: ["Kishtwar"],
    Kulgam: ["Kulgam"],
    Kupwara: ["Kupwara"],
    Poonch: ["Poonch"],
    Pulwama: ["Pulwama"],
    Rajouri: ["Rajouri"],
    Ramban: ["Ramban"],
    Reasi: ["Reasi"],
    Samba: ["Samba"],
    Shopian: ["Shopian"],
    Srinagar: ["Srinagar"],
    Udhampur: ["Udhampur"],
  },
  Ladakh: {
    Kargil: ["Kargil"],
    Leh: ["Leh"],
  },
  Lakshadweep: {
    Lakshadweep: ["Kavaratti"],
  },
  Puducherry: {
    Karaikal: ["Karaikal"],
    Mahe: ["Mahe"],
    Puducherry: ["Puducherry"],
    Yanam: ["Yanam"],
  },
};

// Populate states
window.onload = function () {
  const stateSelect = document.getElementById("state");
  for (const state in locationData) {
    if (state.trim() !== "") {
      // Ensure no blank states are added
      const option = document.createElement("option");
      option.value = state.trim();
      option.textContent = state.trim();
      stateSelect.appendChild(option);
    }
  }
};

// Populate districts based on selected state
function populateDistricts() {
  const stateSelect = document.getElementById("state");
  const districtSelect = document.getElementById("district");
  const citySelect = document.getElementById("city");
  const selectedState = stateSelect.value.trim(); // Ensure no blank selection

  // Clear previous options
  districtSelect.innerHTML = '<option value="">All</option>';
  citySelect.innerHTML = '<option value="">All</option>';

  if (selectedState && locationData[selectedState]) {
    const districts = locationData[selectedState];
    for (const district in districts) {
      if (district.trim() !== "") {
        // Ensure no blank districts are added
        const option = document.createElement("option");
        option.value = district.trim();
        option.textContent = district.trim();
        districtSelect.appendChild(option);
      }
    }
  }
}

// Populate cities based on selected district
function populateCities() {
  const stateSelect = document.getElementById("state");
  const districtSelect = document.getElementById("district");
  const citySelect = document.getElementById("city");
  const selectedState = stateSelect.value.trim();
  const selectedDistrict = districtSelect.value.trim();

  // Clear previous options
  citySelect.innerHTML = '<option value="">All</option>';

  if (
    selectedState &&
    selectedDistrict &&
    locationData[selectedState][selectedDistrict]
  ) {
    const cities = locationData[selectedState][selectedDistrict];
    cities.forEach((city) => {
      if (city.trim() !== "") {
        // Ensure no blank cities are added
        const option = document.createElement("option");
        option.value = city.trim();
        option.textContent = city.trim();
        citySelect.appendChild(option);
      }
    });
  }
}
